### ISSUE TITLE
Add e2e test showing extendibility 

### ISSUE THREAD

**Issue by boolafish** [omisego/plasma-contracts#398]
## Issue Type 

```
[ ] bug report
[x] feature request
```

## Expected Behavior
Add tests to display that `PlasmaFramework` can add new exit games and can transfer a tx from tx type A to tx type B.

- Design a new tx type.
- Write the ExitGame, SpendingCondition, ...etc contracts for new tx type.
- Add e2e tests to move from one tx type to another

## Motivation for Change
Demo and make sure the contract is really extendible.

**Comment by boolafish** [comment]
### Test implementation plan
- Reuse `SpendingConditionRegistry`, `OutputGuardHandlerRegistry`, `PaymentOutputToPaymentTxCondition`, `PaymentOutputGuardHandler`, `PaymentTransactionStateTransitionVerifier` for PaymentV2. Just need to redeploy and inject them to `PaymentExitGame` for V2.
- For simplicity of testing, the new tx type (planning to do a DEX mock), instead of signing it with EIP712, we sign the sha3 of raw tx bytes instead.
- Does not test the exitability of DEX tx. Not much benefit here and too complex.

### Test coverage
- Able to register new exit games
- Able to transfer tx types across txs.
- Able to challenge cross tx type spent txs.

### TODOs:
- [ ] Implement mock `PaymentOutputToDexSpendingCondition`
- [ ] Implement mock `PaymentDexOutputGuardHandler` that handles the output type that can be used as DEX (mock) tx input.
- [ ] Deploy new `PaymentExitGame` with correct injected contracts/values as V2.
- [ ] Tests the challenge for SE on cross type transfer txs.
